version: "3.8"

services:
  pg:
    environment:
      - TZ=Europe/Madrid
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PWD}
      - POSTGRES_DB=${PG_DB}
    image: postgres
    restart: always
    container_name: $PG_CONTAINER_NAME
    command: postgres -c config_file=/etc/postgresql.conf
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:${PG_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  mysql:
    environment:
      - TZ=Europe/Madrid
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    image: mysql
    restart: always
    container_name: $MYSQL_CONTAINER_NAME
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  postgres_data:
  mysql_data:
